namespace AuthGen
{
    public class ClientModel : MetaModelDef
    {
        public ClientModel()
        {
            SetName(Client)
                .SetModuleName(Sso)
                .SetDoNotGenDomainModel()
                .AddProperty(Int(Id)
                    .ExistIn(Dto,DetailDto,SelectDto,RemoveDto))
                .AddProperty(String(ClientName)
                    .ExistIn(Dto, SelectDto, AddDto))
                .AddProperty(String(LogoUri)
                    .ExistIn(Dto, SelectDto))
                .AddProperty(String(Description)
                    .ExistIn(Dto, SelectDto, AddDto))
                .AddProperty(String(ClientId)
                    .ExistIn(Dto, SelectDto, AddDto))
                .AddProperty(String(Enabled)
                    .ExistIn(Dto, DetailDto))
            #region Basic
                 .AddProperty(Bool(RequireRequestObject)
                    .ExistIn( DetailDto))
                  .AddProperty(ListString(AllowedCorsOrigins)
                    .ExistIn( DetailDto))
            #endregion
            #region Authentication
                  .AddProperty(String(FrontChannelLogoutUri)
                    .ExistIn(DetailDto))
                  .AddProperty(Bool(FrontChannelLogoutSessionRequired)
                    .ExistIn(DetailDto))
                   .AddProperty(String(BackChannelLogoutUri)
                    .ExistIn(DetailDto))
                    .AddProperty(Bool(BackChannelLogoutSessionRequired)
                    .ExistIn(DetailDto))
                    .AddProperty(Bool(EnableLocalLogin)
                    .ExistIn(DetailDto))
                     .AddProperty(ListString(IdentityProviderRestrictions)
                    .ExistIn(DetailDto))
                     .AddProperty(Int(UserSsoLifetime)
                    .ExistIn(DetailDto))
            #endregion
            #region Token
                    .AddProperty(Bool(AllowOfflineAccess)
                    .ExistIn(DetailDto))
                       .AddProperty(Int(IdentityTokenLifetime)
                    .ExistIn(DetailDto))
                          .AddProperty(String(AllowedIdentityTokenSigningAlgorithms)
                    .ExistIn(DetailDto))
                    .AddProperty(Int(AccessTokenLifetime)
                    .ExistIn(DetailDto))
                     .AddProperty(Int(AccessTokenType)
                    .ExistIn(DetailDto))
                      .AddProperty(Int(AuthorizationCodeLifetime)
                    .ExistIn(DetailDto))
                       .AddProperty(Int(AbsoluteRefreshTokenLifetime)
                    .ExistIn(DetailDto))
                         .AddProperty(Bool(IncludeJwtId)
                    .ExistIn(DetailDto))
                            .AddProperty(Int(SlidingRefreshTokenLifetime)
                    .ExistIn(DetailDto))
                    .AddProperty(Int(RefreshTokenUsage)
                    .ExistIn(DetailDto))
                     .AddProperty(Int(RefreshTokenExpiration)
                    .ExistIn(DetailDto))
                     .AddProperty(Bool(UpdateAccessTokenClaimsOnRefresh)
                    .ExistIn(DetailDto))
                     .AddProperty(Bool(AlwaysSendClientClaims)
                    .ExistIn(DetailDto))
                      .AddProperty(String(PairWiseSubjectSalt)
                    .ExistIn(DetailDto))
                   .AddProperty(Bool(AllowAccessTokensViaBrowser)
                    .ExistIn(DetailDto))
                      .AddProperty(Bool(AlwaysIncludeUserClaimsInIdToken)
                    .ExistIn(DetailDto))
                     .AddProperty(List(ClientClaim, Claims)
                    .ExistIn(DetailDto))
            #endregion
            #region Device Flow
                    .AddProperty(String(UserCodeType)
                    .ExistIn(DetailDto))
                    .AddProperty(Int(DeviceCodeLifetime,300)
                    .ExistIn(DetailDto))
            #endregion
            #region  Client Credentials
                    .AddProperty(NewProperty(ClientSecret, ClientSecrets,DefaultValue_CtorNew)
                    .ExistIn(DetailDto))
            #endregion
            #region Consent Screen
                     .AddProperty(Bool(AllowRememberConsent)
                    .ExistIn(DetailDto))
                        .AddProperty(Int(ConsentLifetime)
                    .ExistIn(DetailDto))
            #endregion
            #region Properties
                     .AddProperty(List(ClientProperty, Properties)
                    .ExistIn(DetailDto))
            #endregion
                .AddProperty(Enum(ClientTypes, ClientType, "ClientTypes.Web")
                    .ExistIn(Dto, SelectDto,AddDto))
                .AddProperty(ListString(AllowedGrantTypes)
                     .ExistIn(AddDto))
                .AddProperty(Bool(RequirePkce)
                     .ExistIn(AddDto))
                .AddProperty(ListString( RedirectUris)
                     .ExistIn(AddDto))
                .AddProperty(ListString( PostLogoutRedirectUris)
                     .ExistIn(AddDto))
                .AddProperty(String(ClientUri)
                     .ExistIn(AddDto))
                .AddProperty(String(LogoUri)
                     .ExistIn(AddDto))
                .AddProperty(Bool(RequireConsent)
                     .ExistIn(AddDto))
                .AddProperty(Bool(RequireClientSecret)
                     .ExistIn(AddDto))
                .AddProperty(ListString(AllowedScopes)
                     .ExistIn(AddDto))
                .SupportAdd()
                .SupportSelect()
                .SupportDetail()
                .Set_CustomDetailDtoBaseClass(AddDtoName)
                .SupportRemove()
                .SupportUpdate()
                .Set_UpdateDtoInheritDetailDto()

            #region old
            //.AddProperty(Enum(ClientTypes, ClientType, "ClientTypes.Web"))
            //.AddProperty(String(ClientId))
            //.AddProperty(String(ClientName))
            //.AddProperty(String_Description())
            //.AddProperty(ListString( AllowedGrantTypes))
            //.AddProperty(Bool(RequirePkce))
            //.AddProperty(ListString( RedirectUris))
            //.AddProperty(ListString( PostLogoutRedirectUris))
            //.AddProperty(String(ClientUri))
            //.AddProperty(String(LogoUri))
            //.AddProperty(Bool(RequireConsent))
            //.AddProperty(Bool(RequireClientSecret))
            //.AddProperty(ListString( AllowedScopes))
            #endregion
            ;
        }
    }
}
